name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod download

      - name: Build for multiple platforms
        run: |
          mkdir -p build
          platforms=("windows/amd64" "windows/arm64" "linux/amd64" "linux/arm64" "darwin/amd64" "darwin/arm64")
          for platform in "${platforms[@]}"
          do
            platform_split=(${platform//\// })
            GOOS=${platform_split[0]}
            GOARCH=${platform_split[1]}
            output_name=pingood-$GOOS-$GOARCH
            if [ $GOOS = "windows" ]; then
              output_name+='.exe'
            fi
            echo "Building for $GOOS/$GOARCH..."
            CGO_ENABLED=0 GOOS=$GOOS GOARCH=$GOARCH go build -o build/$output_name
          done

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            build/pingood-windows-amd64.exe
            build/pingood-windows-arm64.exe
            build/pingood-linux-amd64
            build/pingood-linux-arm64
            build/pingood-darwin-amd64
            build/pingood-darwin-arm64
          draft: false
          prerelease: false
          generate_release_notes: true